spring:
  application:
    name: hcph-spring-exam
  datasource:
    url: jdbc:h2:mem:myDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8910